### ISSUE TITLE
Inject styles in the opened window?

### ISSUE THREAD

**Issue by tleunen** [JakeGinnivan/react-popout#24] opened 2016-08-30 12:08 UTC
Hey @JakeGinnivan,

First of all, thanks for the component!

Is there a way to inject styles in the opened window? I'd like to style the body for example to remove the default margin it has.

Thanks.

**Comment by isthisstackoverflow** [comment] 2017-01-02 14:31
Same, hence the bump. If you found a way, some directions would be appreciated.

**Comment by donnrriz** [comment] 2017-07-18 14:28
See issue #15

**Comment by marchaos** [comment] 2017-07-24 10:13
I added a means for getting access to the popout window in my branch. This will probably allow you to inject styles into the document or body. 

To get access to the window, use a function for children like so:

```js
<PopoutWindow {...}>
    {popoutWindow => (
            <MyComponent popoutWindow={popoutWindow} />
    )}
</PopoutWindow>
```

Within your componentWillMount() you could set popout.document.body.style.backgroundColor. etc. 

It's a bit if a round about way (not what I added the function behaviour for) but might do for now. I noticed that this project has stagnated since Feb this year. I would be willing to take it over, so could add this functionality via a nicer way if you think it would be useful?

**Comment by marchaos** [comment] 2017-09-27 10:51
Closing as duplicate of https://github.com/JakeGinnivan/react-popout/issues/15

**Closed as completed by marchaos** 2017-09-27 10:51 UTC
Labels: duplicate
