### ISSUE TITLE
IE 11 shows empty Popout if url prop is defined

### ISSUE THREAD

**Issue by limpbrains** [JakeGinnivan/react-popout#8] opened 2015-12-10 15:53 UTC
Popout without url works fine. 
But url it breaks on line 80 of react-popout.jsx

```
win.document.body.appendChild(container);
```

Can't call methon appendChild of null or undefined.

**Comment by JakeGinnivan** [comment] 2016-04-16 03:40
This should be fixed on master now. I can't reproduce the issue

**Closed as completed** 2016-04-16 03:45 UTC
