### ISSUE TITLE
closeWindow example

### ISSUE THREAD

**Issue by jchabot86** [JakeGinnivan/react-popout#27] opened 2016-11-22 21:06 UTC
Is there a closeWindow example?  If I put a "ref" on the <Popout> component, it doesn't seem to end up in the this.refs array.

**Comment by marcellodesales** [comment] 2017-07-28 02:23
The demo shows the correct behavior Opening the component... But with URLs it fails to trigger the method call

**Comment by marchaos** [comment] 2017-09-27 10:29
I suspect this has been fixed in the latest version. Can you retest?

**Comment by marchaos** [comment] 2017-09-27 10:48
Duplicate of https://github.com/JakeGinnivan/react-popout/issues/22

**Closed as completed** 2017-09-27 10:49 UTC
Labels: duplicate
